- name: "update packages"
  ansible.builtin.yum:
    name: '*'
    state: latest
  become: true    


- name: Print return information from the previous task
  ansible.builtin.debug:
    var: package_pip_custom