- name: "deploy app"
  hosts: app
  vars_files:
    - "{{playbook_dir}}/../envs/app-packages.yml"
    - "{{playbook_dir}}/../envs/common.yml"
    - "{{playbook_dir}}/../secrets/sec.yml"

  tasks: 
    - name: set facts
      import_tasks: 00_set_facts.yml #reservated by ansible

    - name: update system packages
      import_tasks: 01_cor_package.yml

    
    - name: config_web server ---- integration
      import_tasks: 02_http_server.yml

    - name: config git and download app ----  integration
      import_tasks: 03_git_set_up.yml
    
    - name: install requirements
      import_tasks: 04_install_dep.yml
